### ISSUE TITLE
Dangling links on files over 4GB?

### ISSUE THREAD

**Issue by franciscolourenco** [brandt/symlinks#1]
I'm trying this tool on in Arch Linux ARM on a Cubieboard and it is incorrectly identifying links pointing to files over 4GB as dangling.

Any idea what could cause this issue?

**Comment by brandt** [comment]
A few questions:
- Are the links and targets on the same filesystem?
- What filesystem(s) are we working with here?
- Did you compile symlinks on the Cubieboard?
- Are the links absolute, relative, or both?
- If relative, do they descend below root? (e.g. `cd /tmp ; touch target ; ln -s ../../tmp/target source`)

In the meantime, I'll poke around and see if anything jumps out at me!

Cheers,
Brandt

**Comment by franciscolourenco** [comment]
Thanks for the quick reply
- Same file system
- ext4
- Compiled on the Cubieboard with https://aur.archlinux.org/packages/sy/symlinks/PKGBUILD
- Both relative and absolute fail
- Nothing below root

**Comment by franciscolourenco** [comment]
Also, if I run symlinks -t on the real files directly it complains with `: Value too large for defined data type` for each file.

**Comment by franciscolourenco** [comment]
Maybe the limit is 2GB instead of 4GB https://www.gnu.org/software/coreutils/faq/coreutils-faq.html#Value-too-large-for-defined-data-type

**Comment by brandt** [comment]
Could you run the script in this gist and let me know what its output is?

https://gist.github.com/brandt/10780920

Just a heads up -- it creates a few files amounting to about 7.2 GiB worth of zeros.

**Comment by franciscolourenco** [comment]
```
Cloning into 'symlinks'...
remote: Reusing existing pack: 38, done.
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 42 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
gcc -Wall -Wstrict-prototypes -O2  -o symlinks symlinks.c
~/symlinks/test ~/symlinks
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.0101694 s, 103 MB/s
1025+0 records in
1025+0 records out
1074790400 bytes (1.1 GB) copied, 20.3437 s, 52.8 MB/s
2049+0 records in
2049+0 records out
2148532224 bytes (2.1 GB) copied, 42.5044 s, 50.5 MB/s
4097+0 records in
4097+0 records out
4296015872 bytes (4.3 GB) copied, 87.3123 s, 49.2 MB/s
~/symlinks

Test: Freshly compiled Symlinks
relative: /home/user/symlinks/test/link_1025 -> file_1025
dangling: /home/user/symlinks/test/link_4097 -> file_4097
/home/user/symlinks/test/file_2049: Value too large for defined data type
relative: /home/user/symlinks/test/link_1 -> file_1
/home/user/symlinks/test/file_4097: Value too large for defined data type
dangling: /home/user/symlinks/test/link_2049 -> file_2049

Test: Installed Symlinks
relative: /home/user/symlinks/test/link_1025 -> file_1025
dangling: /home/user/symlinks/test/link_4097 -> file_4097
/home/user/symlinks/test/file_2049: Value too large for defined data type
relative: /home/user/symlinks/test/link_1 -> file_1
/home/user/symlinks/test/file_4097: Value too large for defined data type
dangling: /home/user/symlinks/test/link_2049 -> file_2049
```

**Comment by brandt** [comment]
I've provisioned a clean i686 Arch VM, but so far I haven't been able to replicate the issue.  I suspect I'm missing something silly, but I haven't figured it out yet!

**Comment by brandt** [comment]
Strike that, I've replicated the issue.

```
Test: Freshly compiled Symlinks
/home/brandt/symtest/symlinks/test/file_4097: Value too large for defined data type
relative: /home/brandt/symtest/symlinks/test/link_1 -> file_1
relative: /home/brandt/symtest/symlinks/test/link_1025 -> file_1025
/home/brandt/symtest/symlinks/test/file_2049: Value too large for defined data type
dangling: /home/brandt/symtest/symlinks/test/link_4097 -> file_4097
dangling: /home/brandt/symtest/symlinks/test/link_2049 -> file_2049
```

**Comment by franciscolourenco** [comment]
How did you manage?

**Comment by brandt** [comment]
The issue was indeed related to large file support (LFS).  My latest commit (tagged v1.4.3) should fix it.

Thanks for bringing it to my attention and for giving me an excuse to play with Arch again! :smile:

**Comment by franciscolourenco** [comment]
It was a pleasure :)
Thank you!
